# Generated by Django 2.0.10 on 2019-03-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='sex',
            field=models.CharField(choices=[('prefer not to say', 'Prefer not to say'), ('male', 'Male'), ('female', 'Female')], default='(select sex)', max_length=12),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
