# Generated by Django 2.0.10 on 2019-04-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisgraph',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
        migrations.AlterField(
            model_name='analysissingle',
            name='annotation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveys.Annotation'),
        ),
        migrations.AlterField(
            model_name='analysissingle',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
    ]
