# Generated by Django 2.0.10 on 2019-03-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='word',
            name='start',
            field=models.IntegerField(),
        ),
    ]
