# Generated by Django 2.0.10 on 2019-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='sex',
            field=models.CharField(choices=[('prefer not to say', 'Prefer not to say'), ('male', 'Male'), ('female', 'Female')], default='(select sex)', max_length=64),
        ),
    ]
