# Generated by Django 2.0.10 on 2019-02-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='pi_set',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='surveys.PersonalInformation'),
        ),
    ]
