# Generated by Django 2.0.10 on 2019-02-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20190223_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='personal_information',
        ),
    ]
