# Generated by Django 2.0.10 on 2019-02-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20190224_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='pi_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='surveys.PersonalInformation'),
        ),
    ]
