# Generated by Django 2.0.10 on 2019-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20190212_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
