# Generated by Django 2.0.10 on 2019-02-17 20:46

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20190212_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(18)])),
                ('sex', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('prefer not to say', 'PREFER NOT TO SAY')], max_length=30)),
                ('country_of_birth', django_countries.fields.CountryField(max_length=2)),
                ('country_of_resedence', django_countries.fields.CountryField(max_length=2)),
                ('sexual_orientation', models.CharField(max_length=256)),
                ('native_tongue', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(max_length=65536),
        ),
    ]
