# Generated by Django 2.0.10 on 2019-02-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20190224_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='pi_set',
        ),
    ]
