# Generated by Django 2.0.10 on 2019-02-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_survey_personal_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='pi_set',
            field=models.ManyToManyField(to='surveys.PersonalInformation'),
        ),
    ]
