# Generated by Django 2.0.10 on 2019-02-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20190213_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.CharField(max_length=100000),
        ),
    ]
