# Generated by Django 2.0.10 on 2019-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_survey_pi_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='pi_choices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
