# Generated by Django 2.0.10 on 2019-02-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20190217_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='sex',
            field=models.CharField(choices=[('prefer not to say', 'Prefer not to say'), ('male', 'Male'), ('female', 'Female')], default='(select sex)', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('S', 'Single choice'), ('M', 'Multiple choices'), ('T', 'Text answer'), ('G', 'Gradient answer')], default=0, max_length=1),
        ),
    ]
