# Generated by Django 2.0.10 on 2019-02-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey_pi_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='piQuestions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveys.PersonalInformation'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey'),
        ),
    ]
