# Generated by Django 2.0.10 on 2019-02-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20190223_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='pi_set',
            field=models.ManyToManyField(to='surveys.PersonalInformation'),
        ),
    ]
