# Generated by Django 2.0.10 on 2019-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20190217_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
