# Generated by Django 2.0.10 on 2019-02-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_survey_pi_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='pi_set',
            new_name='pichoices',
        ),
    ]
