# Generated by Django 2.0.10 on 2019-02-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20190225_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='piQuestions',
            new_name='pi_questions',
        ),
    ]
